name: Vercel Preview Deployment
 workflow_call:
    secrets:
      VERCEL_USER_ID: 
        required: true
        description: "your vercel user ID"

      VERCEL_PROJECT_ID: 
        required: true
        description: "the project ID that u deploy in vercel"

      VERCEL_TOKEN: 
        required: true
        description: "the project ID that u deploy in vercel"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: yarn add --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
