name: "CodeScan"

on:
  workflow_call:
    inputs:
      codeScan_language:
        required: false
        type: string
        default: "javascript-typescript"
      app_repository:
        required: true
        type: string
      app_branch:
        required: false
        type: string
        default: "develop"
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.app_repository }}
          ref: ${{ inputs.app_branch }}
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ inputs.codeScan_language}}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ inputs.codeScan_language}}"
