name: Deploy to aws s3

on:
  push:
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"

  workflow_call:
    secrets:
      AWS_BUCKET: 
        required: true
        description: "AWS S3 bucket"
      AWS_KEY_ID: 
        required: true
        description: "AWS key ID"
      AWS_SECRET_ACCESS_KEY: 
        required: true
        description: "AWS Access key"

    inputs:
      build_name:
        required: true
        type: string

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: ${{ inputs.build_name }}
        
      - name: Upload files to aws
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
