name: Shared Deployment

on:
  workflow_call:
    secrets:
      PAT:
        required: false
        description: "private access token"

      AZURE_PPL:
        required: true
        description: "azure deploy to service publish profile"

      # the build artifact options
      azure_service_name:
        required: true
    inputs:
      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: true
        type: string
        default: UAT

      # the build artifact options
      build_name:
        required: true
        type: string

jobs:
  Shared-Deploy-UAT_TEST:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.ref != 'refs/heads/main' && inputs.currentEnvironment != 'PROD'
    steps:
      - name: Download UAT/TEST artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_name }}

      - name: Deploy to UAT/TEST
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.azure_service_name}}
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZURE_PPL }}

  Shared-Deploy-PROD:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && inputs.currentEnvironment == 'PROD'
    # Only run this step if the branch is main
    steps:
      - name: Download PROD artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_name }}

      - name: Deploy to PROD
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.azure_service_name}}
          publish-profile: ${{ secrets.AZURE_PPL }}
