name: Vercel Preview Deployment

on:
  push:
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"

  workflow_call:
    inputs:
      build_name:
        required: true
        type: string

    secrets:
      PAT:
        required: true
        description: "personal access token"

      VERCEL_USER_ID:
        required: true
        description: "your vercel user ID"

      VERCEL_PROJECT_ID:
        required: true
        description: "the project ID that u deploy in vercel"

      VERCEL_TOKEN:
        required: true
        description: "the project ID that u deploy in vercel"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: ${{ inputs.build_name }}

      - name: Display downloaded files
        run: ls -R

      - name: Install Vercel CLI
        run: |
          yarn global add vercel@latest

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
