name: Shared Deployment

on:
  workflow_call:
    secrets:
      NETLIFY_AUTH_TOKEN:
        required: true
        description: "netlify access token"
      NETLIFY_SITE_ID:
        required: true
        description: "the netlify project ID"

    inputs:
      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: true
        type: string
        default: UAT

      # the build artifact options
      build_name:
        required: true
        type: string

      build_path:
        required: false
        type: string
        default: build

jobs:
  Shared-Deploy:
    environment: ${{ inputs.currentEnvironment }}
    runs-on: ubuntu-latest
    steps:
      - name: Download ${{ inputs.currentEnvironment}} artifacts 
        if: github.ref != 'refs/heads/main' && inputs.currentEnvironment != 'PROD'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_name }}
          path: ${{ inputs.build_path }}

      - name: Deploy to ${{ inputs.currentEnvironment}}
        if: github.ref != 'refs/heads/main' && inputs.currentEnvironment != 'PROD'
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./build"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Download PROD artifacts
        if: github.ref == 'refs/heads/main' && inputs.currentEnvironment == 'PROD'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_name }}
          path: ${{ inputs.build_path }}

      - name: Deploy to PROD
        if: github.ref == 'refs/heads/main' && inputs.currentEnvironment == 'PROD'
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./build"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}