name: Shared Deployment

on:
  workflow_call:
    secrets:
      PAT:
        required: false
        description: "private access token"

      AZURE_PPL:
        required: true
        description: "azure deploy to service publish profile"

      # the build artifact options
      azure_service_name:
        required: true
    inputs:
      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: true
        type: string
        default: UAT

      # the build artifact options
      build_name:
        required: true
        type: string

      # the app that u want to build, one is for frontEnd web, another is for backEnd service
      appType:
        required: false
        type: string
        default: web

jobs:
  Shared-Deploy-UAT_TEST:
    environment: ${{ inputs.currentEnvironment }}
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/main' && inputs.currentEnvironment != 'PROD'

    steps:
      - name: Download UAT/TEST artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_name }}

      - name: Unzip artifacts
        if: inputs.appType == 'service'
        run: unzip artifact.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9BCE3532AA5446FBA564630F640BD2DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E440DBA969964EE5AFDDA9BBDAF90A06 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4087134650F441CABDE0ACD34207C74 }}

      - name: Deploy to UAT/TEST
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.azure_service_name}}
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZURE_PPL }}

  Shared-Deploy-PROD:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && inputs.currentEnvironment == 'PROD'
    # Only run this step if the branch is main
    steps:
      - name: Download PROD artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_name }}

      - name: Unzip artifacts
        if: inputs.appType == 'service'
        run: unzip artifact.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9BCE3532AA5446FBA564630F640BD2DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E440DBA969964EE5AFDDA9BBDAF90A06 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4087134650F441CABDE0ACD34207C74 }}

      - name: Deploy to PROD
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.azure_service_name}}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PPL }}
