name: Shared Deployment

on:
  workflow_call:
    secrets:
      PAT:
        required: false
        description: "private access token"

      AZURE_CLIENT_ID:
        required: true
        description: "azure client ID"

      AZURE_TENANT_ID:
        required: true
        description: "azure tenant ID"

      AZURE_SUB_ID:
        required: true
        description: "azure subsction ID"

      # the build artifact options
      azure_service_name:
        required: true
    inputs:
      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: true
        type: string
        default: UAT

      # the build artifact options
      build_name:
        required: true
        type: string

      # the app that u want to build, one is for frontEnd web, another is for backEnd service
      appType:
        required: false
        type: string
        default: web

permissions:
  id-token: write

jobs:
  Shared-Deploy-UAT_TEST:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    if: github.ref != 'refs/heads/main' && inputs.currentEnvironment != 'PROD'

    steps:
      - name: Download UAT/TEST artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_name }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: Deploy to UAT/TEST
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.azure_service_name }}
          slot-name: "Production"
          package: artifact.zip
          # publish-profile: ${{ secrets.AZURE_PPL }}

  Shared-Deploy-PROD:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.ref == 'refs/heads/main' && inputs.currentEnvironment == 'PROD'

    # Only run this step if the branch is main
    steps:
      - name: Download PROD artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_name }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: Deploy to PROD
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.azure_service_name }}
          slot-name: "Production"
          package: artifact.zip
          # publish-profile: ${{ secrets.AZURE_PPL }}
