name: Netlify Preview Deployment

  workflow_call:
    secrets:
      PAT:
        required: true
        description: "private access token"
      NETLIFY_AUTH_TOKEN:
        required: true
        description: "netlify access token"
      NETLIFY_SITE_ID:
        required: true
        description: "the netlify project ID"

    inputs:
      # the application that u want to deploy

      # the environment that u want to deploy (uat,prod)
      currentEnv:
        required: true
        type: string
        default: UAT
        
      # the build artifact options
      build_name:
        required: true
        type: string

jobs:
  deploy_to_netlify:
    runs-on: ubuntu-latest
    environment: ${{ inputs.currentEnv }}
    steps:

      - name: Get Artifacts
        uses: actions/download-artifact@master
        with:
          name: ${{ inputs.build_name }}
          path: build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./build"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment-environment: ${{ inputs.currentEnv }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
