name: publish docker image

on:
  workflow_call:
    secrets:
      PAT:
        required: true
        description: "private access token"

    inputs:
      # the application that u want to deploy
      app_repository:
        required: true
        type: string

      app_branch:
        required: false
        type: string
        default: develop

      # the environment configs that u want to get
      config_repository:
        required: false
        type: string
        default: aoda-zhang/shared-configs
      config_folder:
        required: true
        type: string

      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: false
        type: string
        default: UAT

jobs:
  Shared-publish-image:
    environment: ${{ inputs.currentEnvironment }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout configs"
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.config_repository }}
          ref: main
          token: ${{ secrets.PAT }}
          path: config

      - name: "Checkout codes"
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.app_repository }}
          ref: ${{ inputs.app_branch }}
          token: ${{ secrets.PAT }}
          path: app

      - name: "Set environment variables"
        run: |
          cp -r ./config/${{ inputs.config_folder }}/. ./app/src/config/.
          mv app/* .
          rm -r app
          rm -r config

      - name: "Set node"
        uses: actions/setup-node@master
        with:
          cache: "yarn"
          check-latest: true
          always-auth: true
          registry-url: "https://registry.npmjs.org"

      - name: "Publish package"
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc && yarn && yarn publish --access=restricted
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}
