name: setEnvironment
on:
  push:
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"

  workflow_call:
    secrets:
      PAT:
        required: true
        description: "private access token"

    inputs:
      # the environment configs that u want to get
      config_repository:
        required: false
        type: string
        default: aoda-zhang/shared-configs
      config_branch:
        required: false
        type: string
        default: main
      config_folder:
        required: true
        type: string

      # the environment that u want to deploy (dev,test,prod)
      currentEnv:
        required: true
        type: string
        default: dev

jobs:
  setEnvironment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout environment configs
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.config_repository }}
          ref: ${{ inputs.config_branch }}
          token: ${{ secrets.PAT }}

      - name: Set environment variables
        run: |
          cd ${{ inputs.config_folder }}/${{ inputs.currentEnv }}
          echo "export $(grep -v '^#' .env | xargs -d '\n')" >> $GITHUB_ENV
        working-directory: ${{ github.workspace }}
