name: shared build

on:
  workflow_call:
    secrets:
      PAT:
        required: true
        description: "private access token"

    inputs:
      # the application that u want to deploy
      app_repository:
        required: true
        type: string

      app_branch:
        required: true
        type: string

      # the environment configs that u want to get
      config_repository:
        required: false
        type: string
        default: aoda-zhang/shared-configs
      config_folder:
        required: true
        type: string

      # the build artifact options
      build_name:
        required: true
        type: string
      build_path:
        required: false
        type: string
        default: build

      # the build script in package.json
      build_script:
        required: false
        type: string
        default: build:UAT

      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: false
        type: string
        default: UAT

      # Is need to deploy by ZIP
      isZipDeploy:
        required: false
        type: string
        default: "false"

jobs:
  Shared-build:
    environment: ${{ inputs.currentEnvironment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout configs
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.config_repository }}
          ref: main
          token: ${{ secrets.PAT }}
          path: config

      - name: Checkout codes
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.app_repository }}
          ref: ${{ inputs.app_branch }}
          token: ${{ secrets.PAT }}
          path: app

      - name: Set environment variables
        run: |
          cp -r ./config/${{ inputs.config_folder }}/. ./app/src/config/.
          cp -r ./config/${{ inputs.config_folder }}/${{ inputs.currentEnvironment }}/. ./app/.

          if [ -d "./app/public" ]; then
          cp -r ./config/${{ inputs.config_folder }}/${{ inputs.currentEnvironment }}/public/. ./app/public/.
          else
            echo "Is backEnd service,no Public folder!"
          fi

          mv app/* .
          rm -r app
          rm -r config

      - name: Set node
        uses: actions/setup-node@main
        with:
          check-latest: true
          cache: "yarn"
          node-version: "20.x"

      - name: Install and Build
        run: |
          yarn --frozen-lockfile && yarn run ${{ inputs.build_script }}

      - name: Zip artifacts
        if: ${{ inputs.isZipDeploy == "true" }}
        run: zip -r artifact.zip dist package.json yarn.lock

      - name: Upload artifacts for service
        if: ${{ inputs.isZipDeploy == "false" }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.build_name }}
          path: artifact.zip

      - name: Upload artifacts for web
        if: ${{ inputs.isZipDeploy == 'false' }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.build_name }}
          path: ${{ inputs.build_path }}
